//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stadium.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserves
    {
        public int İd { get; set; }
        public Nullable<int> SatdiumId { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> CustomerId { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Stadiums Stadiums { get; set; }
    }
}
